name: Blockbreakerblockplacer
version: '${project.version}'
main: com.airplanegobrr.blockbreakerblockplacer.Blockbreakerblockplacer
api-version: 1.18
commands:
  bb:
    description: Add a block breaker!
    usage: /bb
    aliases:
      - blockbreaker
  bp:
    description: Add a block placer!
    usage: /bp
    aliases:
      - blockplacer